// Generate the extension's parser from the app source, never maintain a fork.
import { readFileSync, writeFileSync } from "node:fs";
import ts from "typescript";

const sourceUrl = new URL("../src/lib/meetings/meetingInviteIntake.ts", import.meta.url);
const outputUrl = new URL("meeting-parser.js", import.meta.url);
const compiled = ts.transpileModule(readFileSync(sourceUrl, "utf8"), {
  compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS },
}).outputText;
const output = "// GENERATED by node chrome-extension/build-parser.mjs. Do not edit.\n" +
  "globalThis.ZhiHuiIntake = (() => {\nconst exports = {};\n" + compiled +
  "\nreturn Object.freeze(exports);\n})();\n";

if (process.argv.includes("--check")) {
  if (readFileSync(outputUrl, "utf8") !== output) {
    throw new Error("Extension parser is stale; run node chrome-extension/build-parser.mjs");
  }
  console.log("Shared extension parser is up to date.");
} else {
  writeFileSync(outputUrl, output);
  console.log("Generated extension parser from meetingInviteIntake.ts.");
}
